version: '3.8'
services:
  nestjs:
    build: .
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3001:3000'
    environment:
      POSTGRES_HOST=contenedor_documental-postgres  # Asegúrate de que este nombre coincida con el servicio de contenedor_documental
      POSTGRES_PORT=5432
      POSTGRES_USER=admin
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      POSTGRES_DB=${POSTGRES_DATABASE}
      API_KEY=${API_KEY}
      API_SECRET=${API_SECRET}
    networks:
      - my_network
      - contenedor_documental_default  # Conectar a la red de contenedor_documental
networks:
  my_network:
    external: true
  contenedor_documental_default:
    external: true
