version: '3.8'

services:
  nestjs:
    build: .
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
    networks:
      - my_network
      - contenedor_documental_default

networks:
  my_network:
    external: true
  contenedor_documental_default:
    external: true
